import "./attachment.modal";
import "./form.brick"
import "./frame.brick"
import "./list.brick";
import "./tab.brick";
import "./tab-manager.brick";

import "./inputs/checkbox.brick";
import "./inputs/checkboxes.brick";
import "./inputs/date.brick";
import "./inputs/datetime.brick";
import "./inputs/float.brick";
import "./inputs/integer.brick";
import "./inputs/radio.brick";
import "./inputs/select.brick";
import "./inputs/string.brick";
import "./inputs/text.brick";
import "./inputs/time.brick";
import "./inputs/color.brick";
import "./inputs/combobox.brick";
import "./inputs/fa-icon.brick";
import "./inputs/show.brick";
